project_name: gossboss
before:
  hooks:
    - go mod download
    - go vet ./...
    - go test -cover ./... -count=1
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gossboss/main.go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
dockers:
  - goos: linux
    image_templates:
    - "clapclapexcitement/gossboss:latest"
    - "clapclapexcitement/gossboss:{{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
