---
name: CI/CD

on: [push, pull_request]

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: make

  build-and-publish-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-snapshot
    environment:
      name: release
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Create release tag
        run: make tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker registry
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | \
          docker login docker.io --username clapclapexcitement --password-stdin
      - name: Build & Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
